### PR TITLE
Fix some Bikeshed errors.

### PR DESCRIPTION
**Pull request by mfoltzgoogle**
This fixes some Bikeshed errors and typos in the currently checked in Bikeshed spec.

It also regenerates the HTML from the spec, which includes the contents of PR #119 and PR #120.

### CODE REVIEW

**Comment by mfoltzgoogle** [comment]
It's too difficult to get a meaningful diff for this PR.  I'm going to regenerate the HTML from the top of tree and rebase this.

**Comment by mfoltzgoogle** [comment]
That's better!  Here's the HTML diff.

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwebscreens.github.io%2Fopenscreenprotocol%2F&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fwebscreens%2Fopenscreenprotocol%2F1e918b32eb20bcd4c5e83e93fec7f6f15861881f%2Findex.html

**Comment by mfoltzgoogle** [comment]
Merged as these are editorial fixes.  Feel free to correct anything missed in a followup.

**Comment by pthatcherg** [comment]
Wow, that's a lot of typos.  Thanks for fixing them.

**Pull request merged**
