### PR TITLE
Add material around guest mode.

### PR DESCRIPTION
**Pull request by mfoltzgoogle**
Addresses Issue #41: [Transport] Add section to evaluation indicating compatibility with guest mode

Adds a section to the Transport template for guest mode, and discussion in two existing transports how they could implement guest mode.

### CODE REVIEW

**Comment by mfoltzgoogle** [comment]
PTAL @schien for Data Channel changes
PTAL @louaybassbouss who asked for guest mode evaluation

**Comment by schien** [comment]
Overall this looks good to me. However I don't understand the relationship between WAN support and Guest mode. Is Guest mode not able to be used in LAN? Would be helpful if @mfoltzgoogle can provide some more details.

**Comment by chrisn** [comment]
I agree with @schien's comment. I'm not sure what we mean by Guest mode - e.g., the [documentation for Google Cast](https://developers.google.com/cast/docs/guest_mode) mentions using BLE or ultrasound to communicate locally.

**Comment by mfoltzgoogle** [comment]
@louaybassbouss made the original request to evaluate transports on "guest mode" feasibility and may be able to shed some light.

For this PR, I interpreted "guest mode" to mean: "How to make this transport work for two endpoints that are connected to two distinct LANs and not directly routable."  For example, a private network and a guest network, or a home WiFi network and a cellular data provider.

In general this requires routing the control channel through a WAN that interconnects the two LANs.  In almost all cases of interest "WAN" = "the Internet" and I can simplify the text accordingly.

There are a couple of other potential scenarios that one could call "guest mode":
- How devices that are not on the same LAN (or multicast-restricted because of client isolation) discover each other.  That can be done in a variety of ways including Bluetooth, audio beacons, cloud services etc. The Google Cast guest mode uses some of these techniques.  That's not addressed in this PR.

- Using an alternative physical layer for the same transport/control channel (i.e. Bluetooth PAN).  I didn't mention that in this PR but it could be included if there is interest.

**Comment by louaybassbouss** [comment]
I will also add discovery and handshake to @mfoltzgoogle's interpretation of "guest more".
> For this PR, I interpreted "guest mode" to mean: "How to make this transport work for two endpoints that are connected to two distinct LANs and not directly routable."
As I understood from the [Guest mode documentation for Google Cast](https://developers.google.com/cast/docs/guest_mode) that BLE/Ultrasound/PIN are used for Discovery/pairing but I am not sure about transport. [WiFi-Direct](https://www.wi-fi.org/discover-wi-fi/wi-fi-direct) is one candidate that can be used for both "Discovery" and "Transport" in Guest mode.

**Comment by mfoltzgoogle** [comment]
Discovery, pairing and transport across networks is bigger in scope than what I intend to address here.  My understanding of the webscreens charter [1] is that a complete guest mode stack is out of scope, so an amendment would be required to move forward with that in this repo.
 
[1] https://webscreens.github.io/cg-charter/

**Comment by anssiko** [comment]
@mfoltzgoogle is correct. Quoting the [Scope of Work](https://webscreens.github.io/cg-charter/#scope-of-work):

>The following tasks are in scope for the work of the community group.
>
>1. The specification of a set of network protocols that allows one user agent to use the Presentation API to discover and present Web content on another user agent, when both user agents are connected to the same Local Area Network (LAN).

I suggest proposals that are out of scope for the current charter but that still have merit are tagged as "v2" issues.

**Comment by louaybassbouss** [comment]
agree with @anssiko let's label this issue with v2 and move forward with the v1 features

**Comment by mfoltzgoogle** [comment]
Marked the issue as "v2" and closing this pull request.  It should still be available in the archive when we revisit guest mode.

**Pull request closed without merging**
